name: Dependency tests

on: push
jobs:
  prefer_lowest:
    name: 'Prefer lowest dependency versions'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - uses: ./tests/emulator
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: curl
          php-version: '8.0'

      - name: Install dependencies
        run: composer update --prefer-lowest --no-progress

      - name: Run tests
        run: vendor/bin/phpunit

  locked:
    name: 'Locked dependency versions'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - uses: ./tests/emulator
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: vendor/bin/phpunit
